name: gaseng
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # design pattern
  get: ^4.6.5

  # firebase
  firebase_core: ^2.17.0
  firebase_database: ^10.3.2

  # google
  google_maps_flutter: ^2.3.0
  google_ml_kit: ^0.16.2

  # api interface
  http: ^0.13.6

  # camera & image
  camera: ^0.10.5+5
  image_cropper: ^4.0.1
  carousel_slider: ^4.2.1
  image_picker: ^1.0.4
  image: ^4.1.3
  cached_network_image: ^3.2.3

  # map
  webview_flutter: ^4.4.2
  kpostal: ^0.5.1
  flutter_inappwebview: ^5.8.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  daum_postcode_search: ^0.0.2

  # utils
  json_annotation: ^4.8.0
  flutter_screenutil: ^5.7.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/html/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
